### ISSUE TITLE
HTML is generated but preview doesn't automatically load in browser

### ISSUE THREAD

**Issue by RobertTalbert** [facelessuser/MarkdownPreview#75] opened 2019-03-12 14:50 UTC
Hi, I'm using MarkdownPreview with Sublime Text 3, on a Pixelbook running Linux via Crostini. (ChromeOS version 73.0.3683.57) I have installed the package and all the actions of the package work fine _except_ for previewing in a browser. When I select **Markdown Preview: Preview in Browser** a new Chrome tab opens up but gives the message "Your file was not found / It may have been moved or deleted". In the URL field, the file path `file:///tmp/13.html` is displayed (the number changes depending on how many times I've attempted to preview). 

This happens for all three preview options (github, gitlab, and markdown). I am able to export to HTML and then open the HTML manually in a browser, also am able to export the HTML to within Sublime Text. It just can't seem to find the file to automatically display in a browser.  

Thanks in advance for any thoughts on this.

**Comment by facelessuser** [comment] 2019-03-12 15:10
Does the file not exist? Are there any errors in the Sublime console?

**Comment by facelessuser** [comment] 2019-03-12 15:11
Maybe related to:https://github.com/facelessuser/MarkdownPreview/pull/73?

**Comment by RobertTalbert** [comment] 2019-03-12 15:27
No errors in the console. The file does exist -- if I navigate to `~/tmp/` the HTML file is sitting there. If I choose to export the HTML instead, it goes to the same directory as the original Markdown file. 

I'll have a look at #73 and see if it's related.

**Comment by RobertTalbert** [comment] 2019-03-12 15:47
Update: I don't see any obvious connection to #73 although I could be missing something.

**Comment by facelessuser** [comment] 2019-03-12 16:38
Unfortunately, I don't have a pixel book, so without a clear reproduction path, or some clear indication of why something is going if the rails, this may be difficult.

I'll take a look in a basic Linux environment to see if something turns up. If I can't find any issues :shrug:.

**Comment by RobertTalbert** [comment] 2019-03-12 20:09
No worries. Thanks for the responses and the development.

**Comment by facelessuser** [comment] 2019-04-16 00:30
From what I can tell, this is most likely related to #73 as it was mentioned before. Originally this package was written for Python 2, which had to check the system os and compared against `linux2`. `linux2` is no longer a valid check in Python 3, it is simply `linux`. So, Linux specific browser logic was most likely being skipped due to this old check which has been fixed and officially released in 2.2.3. Hopefully this will be fixed for you as soon as the change is available in Package Control.

I will close this issue for now, but if 2.2.3 does not fix your issue, please do reopen.

**Closed by facelessuser** 2019-04-16 00:30 UTC

**Comment by andanders** [comment] 2024-07-03 05:54
@RobertTalbert I have this issue on version 2.5.0. Would you be so kind as to reopen this issue, if the issue persists for you too?

**Comment by facelessuser** [comment] 2024-07-03 06:02
Please open a new issue with details about your specific environment. Reopening an old issue with no additional info will not be helpful.
