### ISSUE TITLE
Change css that is used to render html

### ISSUE THREAD

**Issue by meldarionqeusse** [facelessuser/MarkdownPreview#122] opened 2021-02-12 11:23 UTC
I would like to change the css that is used to render markdown to html. I tried following the instructions provided here but was not able to load my own css. 

I changed `"gitlab": ["C:\\Users\\username\\Documents\\custom.css"],` instead of default as explained here: https://facelessuser.github.io/MarkdownPreview/usage/#including-css

![image](https://user-images.githubusercontent.com/21668964/107761973-8d354800-6d2c-11eb-86b0-0ee883f7dbc5.png)

**Comment by facelessuser** [comment] 2021-02-12 15:23
I am unaware of there being an issue with this, but I will try and confirm.

@gir-bot remove S: triage
@gir-bot add T: bug, S: needs-confirmation

**Comment by facelessuser** [comment] 2021-03-03 05:15
You will need to post an example of your config so that I can see that you are applying it correctly. I cannot reproduce your issue, so it might be a user error in configuring the settings. I guess it could also be bad CSS, but I can't help with that.

**Comment by facelessuser** [comment] 2021-03-12 02:28
As there has been no further response, I'm closing the issue.

**Closed by facelessuser** 2021-03-12 02:28 UTC
Labels: S: needs-confirmation, T: bug
