### ISSUE TITLE
Sane List ins't working? 

### ISSUE THREAD

**Issue by luispuerto** [facelessuser/MarkdownPreview#78] opened 2019-04-18 10:26 UTC
I think that python markdown [sane list extension](https://python-markdown.github.io/extensions/sane_lists/#sane-lists) isn't working properly since the lists aren't rendering with the correct numbers: 

```
1. one 
2. two 
3. three

Hello. How are you doing?  

4. four 
5. five 
6. six 
```

renders: 

```
<article class="markdown-body"><ol>
<li>one </li>
<li>two </li>
<li>three</li>
</ol>
<p>Hello. How are you doing?  </p>
<ol>
<li>four </li>
<li>five </li>
<li>six </li>
</ol></article>
```
![image](https://user-images.githubusercontent.com/22882880/56354832-09b07b80-61d5-11e9-9d2d-a9d151ecc4a0.png)

Perhaps am I missing something?

**Comment by luispuerto** [comment] 2019-04-18 10:27
PS/ Sane List is in the extension list configuration file. 

```
"markdown_extensions": [
        // Python Markdown Extra with SuperFences.
        // You can't include "extra" and "superfences"
        // as "fenced_code" can not be included with "superfences",
        // so we include the pieces separately.
        "markdown.extensions.footnotes",
        "markdown.extensions.attr_list",
        "markdown.extensions.def_list",
        "markdown.extensions.tables",
        "markdown.extensions.abbr",
        "pymdownx.betterem",
        {
            "markdown.extensions.codehilite": {
                "guess_lang": false
            }
        },
        // Extra's Markdown parsing in raw HTML cannot be
        // included by itself, but "pymdownx" exposes it so we can.
        "pymdownx.extrarawhtml",

        // More default Python Markdown extensions
        {
            "markdown.extensions.toc":
            {
                "permalink": "\ue157"
            }
        },
        "markdown.extensions.meta",
        "markdown.extensions.sane_lists",
        "markdown.extensions.smarty",
        "markdown.extensions.wikilinks",
        "markdown.extensions.admonition",
```

**Comment by facelessuser** [comment] 2019-04-18 19:55
I'm not seeing this issue. When I use `sane_lists`, the second list (after the paragraph) starts with `4`.

Are you sure you are running the correct parser? Make sure you are using the `markdown` parser and not the `github` parser, or some other. Also report any errors found in the console if you have any.

**Comment by luispuerto** [comment] 2019-04-19 06:54
>When I use `sane_lists`

Besides of have it on `"markdown_extensions": [` on settings, do I need to have it enable somewhere? 

>Are you sure you are running the correct parser? Make sure you are using the markdown parser and not the github parser, or some other. Also report any errors found in the console if you have any.

Funnily... with GitHub parser the list correctly work and starts on 4, but not with the markdown parser. 

This is the only thing warning in the console: 
```
MarkdownPreview: Warning: The list format for JS is deprecated, please use the dictionary format.
List support will be removed in the future.
```

**Comment by facelessuser** [comment] 2019-04-19 15:21
Apparently I am using an unreleased version of Python Markdown locally. When I downgraded to the current official release, it appears I am now getting the same behavior you are. I need to look into this more as  I am currently confused why this isn't working.

**Comment by facelessuser** [comment] 2019-04-19 15:45
It seems the issue is definitely specific to the current release of Python Markdown as when I jump back up to the the current unreleased tip of the dependency, the issue is no longer present. I'll probably sync the repo up to the current latest, along with pymdown-extensions, and release those dependencies after ensuring everything is working properly.

It will be easier to to probably just sync than figure out what went awry with the last release.  I've been meaning to get the latest Python Markdown out anyways, but due to the extensive changes, I have to sync the pymdown-extensions release with it as there will be compatibility issues if I don't.

**Comment by facelessuser** [comment] 2019-04-20 19:56
Okay, I understand what the issue is now. It turned out that `lazy_ol` used to be a global parameter that was fed into the `Markdown` class. `lazy_ol` was enabled by default, meaning that it would simply ignore the first number.

In the 3.0 series of Markdown (we are currently using 2.6.11) it was changed to have `sane_lists` control this as well as its other functionality. That is why we have this difference. These global parameters are not exposed in Markdown Preview, and since Markdown 3.0+ will do away with them, it doesn't make sense to add them.

Worst case scenario, I can backport this fix if pushing out the full 3.0+ takes me too long.

**Comment by luispuerto** [comment] 2019-04-21 09:44
great to hear! 🙂 

So I guess you are going to fix it soon, right? or do you need to wait till the release of the new python Markdown?

**Comment by facelessuser** [comment] 2019-04-21 12:55
Current behavior is not a bug. So I'm viewing this more as a feature request. As for when it will get done, it will hopefully be soon, it all depends on my schedule and motivation.

Knowing that 2.6.11 is behaving as intended takes the urgency off though as I am no longer fixing a botched merge, but simply bringing new functionality provided by the latest version. I don't have to wait for a new release, I just need to carve out the time and motivation to get it done.

**Comment by luispuerto** [comment] 2019-04-21 19:01
I don't know if it's really a bug or not... but the reality is we have in the `"markdown_extensions":` the `"markdown.extensions.sane_lists"` and it isn't rendering the list as expected when that extension is in use. 

Anyhow... it's true that the problem isn't dire.

**Comment by facelessuser** [comment] 2019-04-21 19:35
> and it isn't rendering the list as expected when that extension is in use.

This is not a true statement. It is not rendering as expected when reading the current 3.0 documentation, but we are not using Python Markdown 3.0, we are using 2.6.11.

If you read 2.6.11 documentation, you'll find it is working exactly as described: https://github.com/Python-Markdown/markdown/blob/2.6.11/docs/extensions/sane_lists.md.

**Comment by facelessuser** [comment] 2019-09-01 22:25
I hoping to upgrade the Python Markdown dependency very soon. When this is done, this should be fixed.

**Comment by facelessuser** [comment] 2019-11-03 23:32
I've upgraded the Python Markdown library and Pymdown Extensions library. This should be fixed once systems upgrade the dependencies. If it doesn't update (it may take an hour or two to actually trigger an update) you can try running `Satisfy dependencies` from the control panel, and if everything installs okay in the console, restart Sublime.

**Closed by facelessuser** 2019-11-03 23:32 UTC
Labels: feature, markdown-parser

**Comment by luispuerto** [comment] 2019-11-04 06:36
Yeah! Now works perfectly. Thanks a lot!
