### ISSUE TITLE
No file update after save

### ISSUE THREAD

**Issue by johnjeffers** [facelessuser/MarkdownPreview#27] opened 2018-07-05 01:32 UTC
After saving changes in Sublime, I reload in the browser, but it does not update. I'm not using livereload, just doing a manual refresh in the browser. The temp file in /private/var/folders is not being updated on save.

Using the following:
- Mac OS 10.13.5 (High Sierra)
- Sublime 3.1.1 build 3176
- MarkdownPreview 2.1.2
- Firefox 61

At the moment, the only way to see saved changes is to re-invoke MarkdownPreview so it loads in a new browser tab.

Is there any way to fix this?

**Comment by facelessuser** [comment] 2018-07-05 01:46
Did you read here? https://facelessuser.github.io/MarkdownPreview/usage/#livereload.

**Comment by johnjeffers** [comment] 2018-07-05 01:58
I sure did. Does not fix the problem.

**Comment by robinzimmermann** [comment] 2018-07-05 16:24
I came here to report this problem, and I see @johnjeffers created the exact issue I was about to!

The problem description is exactly the same: the temp file in /private/var/folders is not being updated when the `.md` file is saved.

I have used MarkdownPreview successfully in the past, in my current installation, too. But now I am also having this problem.

I spent a couple of hours trying things, and extensively read many articles and issues on Markdown Preview and believe my configuration and everything is correct.

If it's helpful:

* Mac OS 10.13.5 (High Sierra)
* Sublime 3.1.1 build 3176
* MarkdownPreview 2.1.2
* Chrome 67.0.3396.99 (Official Build) (64-bit)

**Comment by facelessuser** [comment] 2018-07-05 16:43
In order to investigate this, I will need **detailed** info on your related settings and your steps for reproducibillity.

The live reload feature was not specifically written by me, but has always been...finicky. Did it occur with recent upgrade?  Do you see errors in the console?  What are your related settings set to? Do you set the LiveReload's plugin option once and never again?  Do you set it each time you restart Sublime?

Details are very important when looking into such issues. Unfortunately, without specific details, I will have to close this.

**Comment by johnjeffers** [comment] 2018-07-05 17:34
Is this dependent on the livereload plugin? I swear this worked previously for me, and I have never used livereload. Always just manually refreshed the browser.

**Comment by facelessuser** [comment] 2018-07-05 17:48
It's dependant for it to auto reload in the browser, but not to regenerate for a manual refresh, but I'd have to verify to make sure we haven't added a check for the love reload plugin.

Regardless, I'll need details in order to investigate.

**Comment by facelessuser** [comment] 2018-07-05 18:08
Also which parser us this for? Love reload will not work for GitHub if oauth key is not found. That is a new thing added to prevent using up allowed GitHub calls with no oauth.

**Comment by johnjeffers** [comment] 2018-07-05 18:30
It is Github, and I was missing an oauth token. It's working now. Thanks for the info. I'll recap here for anyone else that needs it in the future.

1. Go to your Github account's Settings page.
2. Click Developer Settings
3. Click Personal Access Tokens
4. Click Generate New Token. Click the "repo" check box, then Generate Token. Save this token somewhere safe.
5. Open Sublime and go to Preferences -> Package Settings -> Markdown Preview -> Settings
6. In user settings (right-hand column), enter:
```
{
	"enable_autoreload": true,
	"github_mode": "markdown",
	"github_oauth_token": "your github token",
	"github_inject_header_ids": true
}
```

**Comment by facelessuser** [comment] 2018-07-05 18:32
Thanks for the update! This illustrates why details are important in these types of issues.

**Comment by facelessuser** [comment] 2018-07-05 21:13
I will consider this issue closed.

**Closed by facelessuser** 2018-07-05 21:13 UTC
Labels: Insufficient Details

**Comment by robinzimmermann** [comment] 2018-07-06 16:09
That fixed it for me. I missed that detail in the docs.

Thanks for providing the extra detail, @johnjeffers!

**Comment by IllyaMoskvin** [comment] 2021-07-26 00:25
For me, this happened because I forgot to name my file `*.md`. I named it `*.txt` on accident.

It still let me generate a preview of a `*.txt`, but the preview wouldn't update on save afterwards.

Just wanted to make a note for future folks searching for a solution.

**Comment by Moxerchen** [comment] 2022-05-10 15:44
> 对我来说，发生这种情况是因为我忘记了命名我的文件 。我以意外命名。`*.md``*.txt`
> 
> 它仍然允许我生成 一个 预览，但预览不会在保存后更新。`*.txt`
> 
> 只是想为将来寻找解决方案的人做一个笔记。

Thank you. Your note solves the problem that is bothering me.😀
