### ISSUE TITLE
Markdown Preview Unable to Launch Browser

### ISSUE THREAD

**Issue by Salamendrine** [facelessuser/MarkdownPreview#85] opened 2019-07-29 01:39 UTC
Hey, I am trying to use MarkdownPreview to build .md file on macOS with freshly installed package. The settings of MarkdownPreview is 

```
{
    "enable_autoreload": true,
    "browser": "default",
    "enable_highlight": true
}
```

The problem is that every time when I try to preview in default browser (Safari), though the status bar says that "Markdown Preview launched in default browser", there is nothing actually happening in my browser. I tried to change the browser to others like `/Applications/Safari.app` or `/Applications/Google Chrome.app` but it gives `cannot execute "/Applications/Safari.app" `. I also tried to remove and install again the package, but it does not help. It seems that no one before have encountered this exact problem and I wonder if anyone could help me out.

**Comment by facelessuser** [comment] 2019-09-01 22:21
I'll take a look and see if I can reproduce sometime soon. I've never had issues with this, but I'll see.

**Comment by Jax0rz** [comment] 2019-09-05 16:41
Same Problem Here

**Comment by facelessuser** [comment] 2019-09-05 16:46
@Jax0rz details? Is it also macOS etc.

**Comment by Jax0rz** [comment] 2019-09-07 02:51
> @Jax0rz details? Is it also macOS etc.

macOS Catalina with Safari browser

**Comment by Jax0rz** [comment] 2019-09-16 02:16
I solve this problem:
```json
{
     "browser": "/Applications/Safari.app/Contents/MacOS"
}
```

**Comment by facelessuser** [comment] 2019-09-16 02:31
Interesting, I'll have to look into to why it couldn't detect it, or at least properly open when using default.

**Comment by NofelYaseen** [comment] 2019-10-09 18:21
> I solved this problem:
> 
> ```json
> {
>      "browser": "/Applications/Safari.app/Contents/MacOS"
> }
> ```

Does not work for me. I get the error,
cannot execute "/Applications/Safari.app/Contents/MacOS" Please check your markdown preview settings.

**Comment by birkin** [comment] 2019-10-09 21:00
After upgrading to MacOS Catalina, my browser stopped launching, though the status bar said it had. The solution that worked for me, via `Sublime Text -> Preferences -> Package Settings -> Markdown Preview`:

`{ "browser": "/Applications/Safari.app/Contents/MacOS/Safari" }` or...
    
`{ "browser": "/Applications/Brave Browser.app/Contents/MacOS/Brave Browser" }`

I quit and re-opened Sublime Text after each settings update, though that may not have been necessary.

---

**Comment by facelessuser** [comment] 2019-10-09 21:03
Yeah, my mac is too old :cry:. My wife's though is new enough that I can upgrade it to Catalina, if she let's me.

Something seems to have changed, and I'm not sure what. Until I get around to trying it out on  a Catalina install, I can't investigate.

**Comment by NofelYaseen** [comment] 2019-10-10 00:31
> After upgrading to MacOS Catalina, my browser stopped launching, though the status bar said it had. The solution that worked for me, via `Sublime Text -> Preferences -> Package Settings -> Markdown Preview`:
> 
> `{ "browser": "/Applications/Safari.app/Contents/MacOS/Safari" }` or...
> 
> `{ "browser": "/Applications/Brave Browser.app/Contents/MacOS/Brave Browser" }`
> 
> I quit and re-opened Sublime Text after each settings update, though that may not have been necessary.

This worked!

**Comment by facelessuser** [comment] 2019-10-15 05:12
2.2.5 fixes an issue with Catalina. Detecting the default browser should work again. Closing this as a duplicate of #92.

**Closed by facelessuser** 2019-10-15 05:12 UTC
